#!/usr/bin/env ruby
require 'bundler/setup'
require 'optparse'
require 'eltiempo'

options = {}
optparser = OptionParser.new do |opts|
  opts.on("--today PLACE") do |place|
    options[:day] = Date.today
    options[:municipality] = place
    options[:operation] = :general
  end

  opts.on("--av_max PLACE") do |place|
    options[:start] = Date.today.beginning_of_week
    options[:until] = Date.today.end_of_week
    options[:municipality] = place
    options[:operation] = :max
  end

  opts.on("--av_min PLACE") do |place|
    options[:start] = Date.today.beginning_of_week
    options[:until] = Date.today.end_of_week
    options[:municipality] = place
    options[:operation] = :min
  end
end

optparser.parse!
usage     = <<EOS
Please provide...
EOS
# STDERR.puts(usage)
# exit 1

# Eltiempo.reporter(options)
puts options.inspect
