#!/usr/bin/env ruby
require 'bundler/setup'
require 'optparse'
require 'eltiempo'

options = {}
optparser = OptionParser.new do |opts|
  opts.on("--today PLACE") do |place|
    options[:start] = Date.today
    options[:until] = Date.today
    options[:municipality] = place
    options[:operation] = :general
  end

  opts.on("--av_max PLACE") do |place|
    options[:start] = Date.today
    options[:until] = Date.today + 6.days
    options[:municipality] = place
    options[:operation] = :max
  end

  opts.on("--av_min PLACE") do |place|
    options[:start] = Date.today
    options[:until] = Date.today + 6.days
    options[:municipality] = place
    options[:operation] = :min
  end
end

optparser.parse!

Eltiempo.reporter(options)
